"""Esquemas Pydantic."""

from app.schemas.admin import (
    AdminUserPublic,
    AuditLogPublic,
    CsvImportRequest,
    CsvImportResult,
    PinResetRequest,
    PinResetResponse,
    UserStatusUpdate,
)
from app.schemas.auth import (
    ChangeCredentialsRequest,
    LoginStaffRequest,
    LoginStudentRequest,
    LogoutRequest,
    RefreshRequest,
    TokenResponse,
    UserPublic,
)
from app.schemas.common import ErrorDetail, HealthResponse
from app.schemas.content import (
    AnnouncementCreate,
    AnnouncementPublic,
    AnnouncementUpdate,
    SectionCreate,
    SectionPublic,
    SectionUpdate,
)
from app.schemas.course import (
    ClassroomResponse,
    ClassroomSeat,
    CourseCreate,
    CoursePublic,
    CourseUpdate,
    EnrollmentCreate,
    EnrollmentPublic,
    SeatAssign,
    SeatPublic,
)
from app.schemas.work import (
    AssignmentCreate,
    AssignmentPublic,
    AssignmentUpdate,
    EvaluationCreate,
    EvaluationPublic,
    SubmissionCreate,
    SubmissionFilePublic,
    SubmissionPublic,
    SubmissionUpdate,
)

__all__ = [
    "AdminUserPublic",
    "AnnouncementCreate",
    "AnnouncementPublic",
    "AnnouncementUpdate",
    "AssignmentCreate",
    "AssignmentPublic",
    "AssignmentUpdate",
    "AuditLogPublic",
    "ChangeCredentialsRequest",
    "ClassroomResponse",
    "ClassroomSeat",
    "CourseCreate",
    "CoursePublic",
    "CourseUpdate",
    "CsvImportRequest",
    "CsvImportResult",
    "EnrollmentCreate",
    "EnrollmentPublic",
    "ErrorDetail",
    "EvaluationCreate",
    "EvaluationPublic",
    "HealthResponse",
    "LoginStaffRequest",
    "LoginStudentRequest",
    "LogoutRequest",
    "PinResetRequest",
    "PinResetResponse",
    "RefreshRequest",
    "SeatAssign",
    "SeatPublic",
    "SectionCreate",
    "SectionPublic",
    "SectionUpdate",
    "SubmissionCreate",
    "SubmissionFilePublic",
    "SubmissionPublic",
    "SubmissionUpdate",
    "TokenResponse",
    "UserPublic",
    "UserStatusUpdate",
]
